### ISSUE TITLE
Can support WebStorm breakpoint ?

### ISSUE THREAD

**Issue by twoeo** [TypeStrong/ts-node#188]
Can I debug in WebStorm running as ts-node?

**Comment by blakeembrey** [comment]
Probably not. There's no API for dynamic source maps and isn't really a `ts-node` issue but a node.js issue. If it's possible, someone can point me to, until then see https://github.com/TypeStrong/ts-node/issues/46.

**Comment by twoeo** [comment]
NodeJS can debug in Webstorm, and WebStorm support to specify a node Runner
(Run / Edit Configurations / Node.js / Node interpreter)

I tried to set it as `ts-node`

Seems WebStorm run a debug command as:
```
D:\Program Files (x86)\JetBrains\WebStorm 2016.2.1\bin\runnerw.exe" C:\Users\King\AppData\Roaming\npm\ts-node --debug-brk=59672 --expose-debug-as=v8debug E:\test\test.ts
```

If NodeJS , it should be:
```
XXX\runnerw.exe" XXX/node.exe --debug-brk=59672 --expose-debug-as=v8debug XXX.js
```

and finally got a error:
```
CreateProcess failed with error 193 (no message available)
```

So don't know if it's a problem about params `--debug-brk=59672` `--expose-debug-as=v8debug`

**Comment by blakeembrey** [comment]
Yes, I know. This, as I mentioned, is related to source maps. Even if you can debug (which you can) there's no point because it doesn't know where the debugger is located in relation to the TypeScript file.

**Comment by ncochard** [comment]
In case it is useful to somebody...

Debugging in WebStorm using ts-node works well on a Mac.
Unfortunately, it does not work well on Windows because of the following bug which was fixed yesterday.
https://youtrack.jetbrains.com/issue/WEB-21753

Hopefully, a new release of WebStorm will soon be available with this fix.

**Comment by ncochard** [comment]
@cevek I've prepared a sample project at the following URL.
https://github.com/ncochard/sample-ts-project.git
If I have not made any mistake, you should be able to just clone that project (on your Mac), place a breakpoint in the unit tests and start debugging.

**Comment by cevek** [comment]
@ncochard Thank you! That works for me!

**Comment by thed0ctor** [comment]
For anyone who is still having issues (for me I didn't want to use mocha just debug typescript files). If you add `--require ts-node/register` to Additional Parameters for node it should work. (see image)
<img width="1183" alt="screen shot 2017-03-16 at 12 01 38 pm" src="https://cloud.githubusercontent.com/assets/3771427/24013967/64d9c636-0a40-11e7-8df6-cfddc9aa783e.png">

**Comment by sinedied** [comment]
@thed0ctor Thank you so much!! I've been struggling with this, and just adding this magical `--require ts-node/register` made it work 👍

**Comment by thed0ctor** [comment]
@sinedied it's actually supposed to be in the "node parameters" box. I ran into issues when I added arguments to my app

**Comment by sinedied** [comment]
Yes, I did that but I can't make webstorm breakpoints to work using just `ts-node` and not the `tsc` compiler. I'm on OSX by the way.

**Comment by thed0ctor** [comment]
@sinedied I'm using IntelliJ IDEA which shouldn't make a difference. Do you have a simple hello world project that recreates the issue? And I mean bare minimum simple project

**Comment by sinedied** [comment]
@thed0ctor when making a simple project to demonstrate the issue, I found the solution: I was using the `"mapRoot": "./"` option is `tsconfig.json`, removing it made debugging works! :tada:

The problem is that automatic imports are not so nice now, but hell yeah I can debug properly!

**Comment by josephfinlayson** [comment]
@sinedied can you share your solution?

**Comment by sinedied** [comment]
Here is my `tsconfig.json`:
```js
{
  "compilerOptions": {
    "lib": ["es6"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es6",
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [ "node_modules/@types" ]
  }
}
```

**Comment by martinsik** [comment]
I think the path in `ts-node` has changed and it should be now `--inspect --require ts-node/register`

**Comment by La-source** [comment]
A big thank you for your @sinedied response that works great.

By cons, how to adapt for npm? In my project I use `process.env` variable positioned by npm which I do not have via the debugger since it is node and not npm.

**Comment by sinedied** [comment]
@La-source You can set environment variables in webstom tasks too. Instead of a NodeJS task, you can create a NPM tasks, and use the same node parameters in your NPM script as shown on the screenshot above.

**Comment by jasonLiu001** [comment]
> @sinedied Thanks. I have solved my trouble according to your comment. Very helpful.

**Comment by Evilart86** [comment]
just configure _ts-node_ interpreter

1. Install _ts-node_: `npm i ts-node --save`
2. Add configuration
![image](https://user-images.githubusercontent.com/20624473/49687503-49bb6f80-fb0c-11e8-9fbe-7a3f7ccb58cb.png)
3. Choose Node.js Configuration template
![image](https://user-images.githubusercontent.com/20624473/49687531-e3831c80-fb0c-11e8-884c-c530f2405fb9.png)
4. Choose Working directory and JavaScript file(your Typescript entry point)
![image](https://user-images.githubusercontent.com/20624473/49687314-d7e22680-fb09-11e8-8957-e3ad4ae57c07.png)
5. Add _ts-node_ interpreter: click `+` and `"Add Local..."` 
![image](https://user-images.githubusercontent.com/20624473/49687407-e2e98680-fb0a-11e8-871e-087fec5115cb.png)
6. Find installed _ts-node_ interpreter (our first step)
![image](https://user-images.githubusercontent.com/20624473/49687475-dade1680-fb0b-11e8-8db3-3877004c43b1.png)
7. Choose interpreter
![image](https://user-images.githubusercontent.com/20624473/49687458-a66a5a80-fb0b-11e8-9379-9e08702bbf37.png)
8. Final configs
![image](https://user-images.githubusercontent.com/20624473/49687252-36f36b80-fb09-11e8-82bd-e8e79ef0df2f.png)

**Ready**
You can run and debug your code

**Comment by Jeff-Tian** [comment]
I made it work by add a `script` to `package.json` as follows:

```
node $NODE_DEBUG_OPTION --require ts-node/register src/index.ts
```

So I can click "debug" button to start the debug session:

![image](https://user-images.githubusercontent.com/3367820/54893256-e0f7d780-4eef-11e9-8628-5533c2b6cf70.png)

![image](https://user-images.githubusercontent.com/3367820/54893275-ec4b0300-4eef-11e9-9809-fa31265d5cf9.png)

**Comment by QuantumInformation** [comment]
Anyone managed to get it to work with ts-node-dev?

https://github.com/whitecolor/ts-node-dev/issues/75

**Comment by LastKing** [comment]
webstorm 2019
ts-node @ 7.x
typescript @ 3.7.x
npm typescript 
![image](https://user-images.githubusercontent.com/8540374/72450045-a2236d00-37f4-11ea-97ca-f56ca4ed3ece.png)

i use the config can debug typescript file .

**Comment by xusai2014** [comment]
> I made it work by add a `script` to `package.json` as follows:
> 
> ```
> node $NODE_DEBUG_OPTION --require ts-node/register src/index.ts
> ```
> 
> So I can click "debug" button to start the debug session:
> 
> ![image](https://user-images.githubusercontent.com/3367820/54893256-e0f7d780-4eef-11e9-8628-5533c2b6cf70.png)
> 
> ![image](https://user-images.githubusercontent.com/3367820/54893275-ec4b0300-4eef-11e9-9809-fa31265d5cf9.png)

It's great.
The solution is approriate for Babel-node debug
