### ISSUE TITLE
Support for --trace-warnings option?

### ISSUE THREAD

**Issue by bitliner** [TypeStrong/ts-node#465]
I would need to run ts-node and print stack trace for unhandled promise exceptions.

How to pass an option `--trace-warnings`?

**Comment by blakeembrey** [comment]
Feel free to submit a PR. It would need to be added to https://github.com/TypeStrong/ts-node/blob/c57ded2881debf773af7b8e01cb652d48f8655ca/src/bin.ts#L19. This code may be refactored before 4.0 though because of https://github.com/TypeStrong/ts-node/issues/459 and would also result in resolving this.

**Comment by stelcheck** [comment]
@bitliner made a PR to add the flag, see https://github.com/TypeStrong/ts-node/pull/476

**Comment by blakeembrey** [comment]
@stelcheck If you can split out this issue with the other one, I can merge one before the other.

**Comment by stelcheck** [comment]
Done.

**Comment by kateile** [comment]
@stelcheck how to use it?
I tried adding script in package.json as
` "dev": "ts-node --trace-warnings  src/server.tsx",`
but i get error when run it

**Comment by stelcheck** [comment]
Have a look at https://medium.com/the-node-js-collection/node-options-has-landed-in-8-x-5fba57af703d - this should allow you to define Node.JS flags and options through environment variables.

**Comment by Elyx0** [comment]
Doesn't work @stelcheck still getting the error on --trace-warnings

**Comment by Elyx0** [comment]
```
node  --trace-warnings -r ts-node/register -r tsconfig-paths/register ./src/index.ts
```
For future reference, this worked

**Comment by LeonardoRick** [comment]
should I be able to run `ts-node --trace-warnings` in 2020?

**Comment by cspotcode** [comment]
In 2020 specifically, you're supposed to do this: https://github.com/TypeStrong/ts-node/issues/465#issuecomment-659375861

If you find yourself in 2019, you might need to do something else.

**Comment by Psychosynthesis** [comment]
> In 2020 specifically, you're supposed to do this: [#465 (comment)](https://github.com/TypeStrong/ts-node/issues/465#issuecomment-659375861)
> 
> If you find yourself in 2019, you might need to do something else.

It work, but looks awful. Why can't just add a parameter to the ts-node section in the config?

**Comment by cspotcode** [comment]
@Psychosynthesis This has been discussed many times before, but the short of it is: not possible because we don't spawn a subprocess.  Doing so adds extra complexity for users and maintainers, and incurs a performance penalty.

**Comment by LeanKhan** [comment]
`ts-node-dev --trace-warnings --respawn --transpileOnly ./src/server.ts`

I use this and it works 🤔

**Comment by benallfree** [comment]
> `ts-node-dev --trace-warnings --respawn --transpileOnly ./src/server.ts`
> 
> I use this and it works 🤔

Doesn't work. When I run it, I get:

```
ts-node-dev: no script to run provided
Usage: ts-node-dev [options] script [arguments]
```

**Comment by LeanKhan** [comment]
@benallfree for a previous version of ts-node 

`^1.0.0-pre.39` it stopped working when I updated it. Now I have to find an alternative or rollback to that version...

**Comment by aymantaybi** [comment]
for anyone who wants to run ts-node and print stack trace for unhandled promise exceptions.

node --loader ts-node/esm --trace-warnings exemple/index.ts

make sure to have ts-node installed as a dev dependency.

**Comment by rafalfigura** [comment]
I was able to achieve that with env variable:
```
NODE_OPTIONS='--trace-warnings'
```
