### ISSUE TITLE
8.0.3 breaks project with: Unable to require `.d.ts` file

### ISSUE THREAD

**Issue by hakan0xFF** [TypeStrong/ts-node#797]
Hey, today I upgraded the ts-node package to the newest version 8.0.3 and it now throws an exception: 

```
TypeError: Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `graphql.schema.ts`.
    at getOutput (backend/server/node_modules/ts-node/src/index.ts:343:15)
    at Object.compile (backend/server/node_modules/ts-node/src/index.ts:368:11)
    at Module.m._compile (backend/server/node_modules/ts-node/src/index.ts:414:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Object.require.extensions.(anonymous function) [as .ts] (backend/server/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

The version 8.0.2 works. I had no time to find the exact cause.

**Comment by izatop** [comment]
I spent some time after upgrade dependencies to find out who broke my project. I installed previous version of the package and it solved issue.

**Comment by hakan0xFF** [comment]
It seems that this [commit](https://github.com/TypeStrong/ts-node/commit/c21569372e0d8ba79c059771929d18568a910c77) broke my project.

**Comment by murbanowicz** [comment]
The same problem here.

**Comment by andyianriley** [comment]
same here

**Comment by whxaxes** [comment]
@blakeembrey any progress for this ?

**Comment by blakeembrey** [comment]
Does anyone want to provide a reproduction or test case?

**Comment by mfellner** [comment]
I am running into this issue with ts-node 8.0.3 and yarn workspaces. I was able to reproduce the issue in this minimal example: https://github.com/mfellner/ts-node-issue-797

8.0.2 does not exhibit the problem. Hope that helps!

**Comment by svi3c** [comment]
I've got this problem in a customer project, so I cannot share code.
For me this happens with yarn workspaces, but not every import from another linked package from the workspaces fails. I could not make out the difference yet.
When I find some time, I'll investigate.

**Comment by svi3c** [comment]
I can confirm that this happens to me with yarn workspaces, too. But not every import from another workspace package fails. For example I've got a package with only type declarations and an import of those does not crash.

**Comment by nolazybits** [comment]
yup, same problem.
Also using yarn workspaces.
Also I have added 
```
  "resolutions": {
        "ts-node": "8.0.2"
  },
```

so ts-node-dev for instance use the right version (and not the latest broken 8.0.3)

**Comment by alcuadrado** [comment]
I think it may be related to using `--files` and having `tsconfig.json`'s `"include"` field matching `.d.ts` files.

**Comment by mikebm** [comment]
Still an issue in 8.1.0.

**Comment by jLouzado** [comment]
- Try running `tsc` before running your project.
- Solved that for my project:
    - https://github.com/action-land/action-land/commit/ec0ce27bba7009d17157b77d196667e5037de2ca#diff-354f30a63fb0907d4ad57269548329e3R15

**Comment by kevinrambaud** [comment]
I confirm that the solution suggested by @jLouzado works well.

```json
{
  "scripts": {
    "pretest": "tsc",
    "test": "mocha -r ts-node/register"
  }
}
```

**Comment by gianmarcotoso** [comment]
I solved by adding `"preserveSymlinks": true` to my `tsconfig.json` file. This was happening within a `lerna` project, so YMMV.

**Comment by ChristianIvicevic** [comment]
@gianmarcotoso Thank you for your suggestion, this helped me to resolve the issue in a similar setup. Furthermore enabling `--transpile-only` would've solved this as well which was a dirty fix though.

**Comment by ChristianIvicevic** [comment]
@gianmarcotoso Minor update: `preserveSymlinks` is causing issue in my case. In a library inside the monorepo that is not transpiled to JS and included as-is changes are not propagated to the main application source files unless the TS server is restarted which is apparently by design as can be seen here: microsoft/TypeScript/issues/30447

Currently I am experimenting with only creating a typings file or reverting to `--transpile-only` in the meantime.

**Comment by SOF3** [comment]
I am able to reproduce this issue reliably, and `preserveSymlinks` indeed solves the problem.

Given these files:
```
$ cat /test/foo/package.json
{
  "name": "foo"
}

$ cat /test/foo/foo.ts
export function foo(){ console.info("Hello world) }

$ cat /test/bar/package.json
{
  "name": "bar"
}

$ cat /test/bar/bar.ts
import {foo} from "foo/foo"
foo()
```

1. `cd /test/foo && npm link`
2. `cd /test/bar && npm link foo`
3. `cd /test/bar && ts-node bar`

One can reliably get this error:
```

/usr/lib/node_modules/ts-node/src/index.ts:368                                                                                                                                                                             throw new TypeError(                                                                                                                                                                                                     ^                                                                                                                                                                                                    TypeError: Unable to require `.d.ts` file.                                                                                                                                                                         This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `foo.ts`.               at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:368:15)                                                                                                                                                   at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:393:11)                                                                                                                                              at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:439:43)                                                                                                                                           at Module._extensions..js (internal/modules/cjs/loader.js:712:10)                                                                                                                                                  at Object.require.extensions.(anonymous function) [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:442:12)                                                                                                     at Module.load (internal/modules/cjs/loader.js:600:32)                                                                                                                                                             at tryModuleLoad (internal/modules/cjs/loader.js:539:12)                                                                                                                                                           at Function.Module._load (internal/modules/cjs/loader.js:531:3)                                                                                                                                                    at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                                                          at require (internal/modules/cjs/helpers.js:22:18)
--
```

By (only) adding this file:
```
$ cat /test/bar/tsconfig.json
{
  "compilerOptions": {
    "preserveSymlinks": true
  }
}
```

`ts-node bar` would successfully output "Hello world".

**Comment by hakan0xFF** [comment]
I can confirm that adding `"preserveSymlinks": true` to `tsconfig.json` solves my problem too.

So moving from version `<=8.0.2` to `>8.0.2` seems to be somehow a breaking change if you are using symlinks..

**Comment by zacaj** [comment]
Running into this as well.  preserveSymlinks seems to fix it, but I don't understand why.  This error message is not very helpful at finding the issue

**Comment by blakeembrey** [comment]
It looks like the issue was introduced when trying to better conform to the TypeScript compiler API by adding `realpath`: https://github.com/TypeStrong/ts-node/commit/c21569372e0d8ba79c059771929d18568a910c77#diff-f41e9d04a45c83f3b6f6e630f10117feR296. Happy to remove this and add back in a new major release, can anyone confirm removing this single line resolves things?

I'll also look into improving this error when I can, it hadn't come up in the past that the TypeScript compiler would give empty files back except when compiling `.d.ts` files - so the error was unfortunately a red herring trying to help some people who do require a `.d.ts` file.

**Comment by hakan0xFF** [comment]
> Happy to remove this and add back in a new major release, can anyone confirm removing this single line resolves things?

Yes, removing the `realpath` line and `"preserveSymlinks": true` from `tsconfig.json` resolves this issue, at least for me. 👍

**Comment by connor4312** [comment]
I've also just run into this in a totally separate scenario: I had mocha set to `require` a file that installed the ts-node loader via `.register()`, and also had an old reference in my nyc config that required `ts-node/register`-- it seems that registering ts-node twice can cause this issue.

Definitely an edge case but maybe ts-node should emit a warning or error if it's registered twice. (I think a no-op would be less desirable, since someone might be trying to register it with different options and wondering why none of the options are having any effect.)

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/commit/9691206def28405d4e53c5a7753f96d15be46e79 for now, does anyone know if this behavior is desirable (aside from being a breaking change right now). Released in 8.1.1. For double registering, see https://github.com/TypeStrong/ts-node/issues/409 - would love to see a PR 😄

**Comment by TorstenStueber** [comment]
Turns out that this actually is a breaking change that causes problems when using pnpm – see https://github.com/TypeStrong/ts-node/issues/876.

**Comment by skjo0c** [comment]
This error is shown if I put my files inside src folder but not if I put them outside src. Does anyone know how to deal with it? I have tried preserveSymlinks but no luck. `ts-node` version is `8.3.0`

**Comment by matthew-dean** [comment]
This is still an issue as of 8.4.1, and the `preserveSymlinks` doesn't seem to fix it.

**Comment by blakeembrey** [comment]
@matthew-dean Can you create a reproduction?

**Comment by matthew-dean** [comment]
@blakeembrey In my case, I think it was actually because my mocha test path was set to `**/__tests__/*.ts`, which I think was then globbing `node_modules`, and some `.ts` file in there was failing. I fixed it by making sure I was globbing `src/**/__tests__/*.ts`

**Comment by matthew-dean** [comment]
@blakeembrey So maybe in my case, the error was legitimate because some node module had a test `.ts` file which wasn't actually compilable. 🤷‍♂

**Comment by stewartmcgown** [comment]
Another edge case for people who get here via 'cannot require `.d.ts` file:

I had a folder in my `src` called `graphql` where I was storing queries, mutations etc, but it required the module `graphql`. Since I had `baseUrl` set to `src`, ts-node was resolving the attempted reference to the npm module `graphql` to the folder that was asking for it.

**Comment by bvalosek** [comment]
For anybody else who finds this from googling, my (probably very narrow) edge case:

* we have a lerna mono repo, with all TS files in a `src` directory per package
* we also have an `index.ts` at the root of each package for package exports
* our `includes` array in tsconfig was `"./packages/*/src/**/*.ts"`
* this all worked fine until it didn't. tsc ran fine but _running tests with ts-jest didnt_. It was throwing the error mentioned in this issue after some changes to the local dep graph.

my solution was to add `"./packages/*/index.ts"` to the `includes` array in tsconfig, and it worked fine after that.

**Comment by IonelLupu** [comment]
@bvalosek In my case, it didn't solve the error. (I am not using lerna) 😥

This is still an issue on `"ts-node": "8.10.1"`

**Comment by sidferreira** [comment]
I think this is related to `"moduleResolution": "node"` that is limited on types ( https://www.typescriptlang.org/docs/handbook/module-resolution.html#node ). 

I have a project with TS and Babel and I added `.d.ts` to the `'module-resolver'` and it fixed the issue.

I'm just trying to find out how to connect `ts-node` to it... if I run `tsc` it works all good. If I run `tsc` only targeting my `CLI` (that is run with `ts-node`) things goes sideways.

**Comment by Morriz** [comment]
As @IonelLupu said this is still an issue, even with `8.10.2`. Renaming the conflicting `.d.ts` file to not use `.ts` resolves the problem, but only after a restart of the typescript server. We don't use babel and tsc works fine.

**Comment by rajitha1998** [comment]
I am also facing the same issue with `"ts-node": "^8.10.2"` @blakeembrey. I am using yarn workspaces and Lerna.

**Comment by hanatharesh2712** [comment]
I have resolved this issue by mentioning the file path in root of **tsconfig.ts** file

`"files": [ "node_modules/package-name/index.ts" ]`

**Comment by fresheneesz** [comment]
I'm seeing this bug with a very basic script: just `console.log("test")` just to see it working. When my `tsconfig.json` contained `"isolatedModules": true` and when I named the file `test.d.ts` I get the error `TypeError: Unable to require file...`. It seems removing the `isolatedModules` constraint solves this. But it doesn't seem like that option should have anything to do with it. My file had no imports at all. AFAICT, something is going wrong here.
